<?
/**
 * Grid Page View
 *
 * @package   Molajo
 * @license   http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright 2013 Amy Stephen. All rights reserved.
 */

?>
<include type=template name=Toolbar/>
    <include type=template name=Formbegin/>
        <include type=template name=Gridfilters wrap=nav wrap_class=grid-filters role=nav/>
            <section class="grid">
                <include type=template name=Gridordering/>
                    <include type=template name=Gridstatus/>
                        <include type=template name=Gridpermissions/>
                            <include type=template name=Gridcategories/>
                                <include type=template name=Gridtags/>
                                    <include type=template name=Gridfeature/>
                                        <include type=template name=Gridsticky/>
                                            <include type=template name=Gridcheckin/>
                                                <include type=template name=Grid role=main/>
                                                    <include type=template name=Pagination wrap=nav
                                                             wrap_class=pagination/>
            </section>
            <include type=template name=Formend/>
