<?
/**
 * Formselectlist Template View
 *
 * @package   Molajo
 * @license   http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright 2013 Amy Stephen. All rights reserved.
 */
?>
<select <? echo $this->row->multiple; ?>name="<? echo $this->row->listname; ?>" class="inputbox">
<? if ($this->row->multiple == '') { ?>
    <option value=""><? echo $this->language->translate(
            'SELECT_' . strtoupper($this->row->listname)
        ); ?></option>
<? } else { ?>
    <option value=""><? echo $this->language->translate('No selection'); ?></option>
    <option value="#"><? echo $this->language->translate('Select all'); ?></option>
<?
}
