<?
/**
 * Gridordering Template View
 *
 * @package   Molajo
 * @license   http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright 2013 Amy Stephen. All rights reserved.
 */
use Molajo\Service;

?>
<div class="grid-ordering grid-batch">
    <ol class="grid-batch">
        <li><strong><? echo $this->language->translate('Order Results'); ?></strong></li>
        <li>
            <include type=template name=formselectlist datalist=Fields selected=<? echo $this->registry->get(
                'Grid',
                'Tableordering'
            ); ?>/>
        </li>
        <li>
            <include type=template name=formselectlist datalist=OrderingDirection selected=<? echo Services::Registry(
            )->get(
                    'Grid',
                    'Orderingdirection'
                ); ?>/>
        </li>
        <li>
            <include type=template name=formselectlist datalist=Itemsperpage
                     selected=<? echo $this->registry->get(
                'Grid',
                'ItemsPerPage'
            ); ?>/>
        </li>
        <li><input type="submit" class="submit button small radius" name="submit" id="Sort" value="Sort"></li>
    </ol>
</div>
