<?php

/**
 * @package   Molajo
 * @copyright 2013 Amy Stephen. All rights reserved.
 * @license   http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <article class="nine columns">
        <include type=template name=blog class=right,secondary,small,button wrap=section role=main/>
            <?php if ((int)$this->registry->get('parameters', 'enable_response_comments') == 1) { ?>
                <aside class="row" role="complementary">
                    <div class="twelve rows">
                        <ul class="link-list right">
                            <li><a href="#" class="fc-webicon facebook">Like us on Facebook</a></li>
                            <li><a href="#" class="fc-webicon twitter">Like us on Facebook</a></li>
                            <li><a href="#" class="fc-webicon googleplus">Like us on Facebook</a></li>
                        </ul>
                        <hr/>
                        <include type=template name=Author wrap=div wrap_class=author-profile/>
                            <section>
                                <include type=template name=Comment wrap=none/>
                                    <include type=template name=Comments wrap=none/>
                                        <include type=template name=Commentform wrap=none/>
                            </section>
                    </div>
                </aside>
            <?php } ?>
    </article>
    <include type=template name=Sidebar wrap=aside wrap_class=three,columns role=complementary/>
</div>
<div class="row">
    <include type=template name=paging wrap=nav role=navigation wrap_class=paging/>
</div>
