<?
/**
 * Author Template View
 *
 * @package   Molajo
 * @license   http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright 2013 Amy Stephen. All rights reserved.
 */

?>
<section itemscope itemtype="http://data-vocabulary.org/Person">
    <h1 itemprop="name">
        <? echo $this->row->author_full_name; ?>
    </h1>
    <? if ($this->row->author_parameters_display_gravatar == 1) { ?>
        <p>
            <img class="gravatar float_left" src="<? echo $this->row->author_email_gravatar; ?>" itemprop="photo"
                 alt="[<? echo $this->row->author_full_name; ?>]">
        </p>
    <? } ?>
    <p>
        <a href="<? echo $this->row->author_catalog_sef_request; ?>"
           title="<? echo $this->language->translate('Posts by '); ?>
            <span itemprop=" name">
        <? echo $this->row->author_full_name; ?>
        </span>
        </a>
    </p>
    <? if ($this->row->author_parameters_display_phone == 1) { ?>
        <p itemprop="tel">
            <? echo $this->row->author_phone; ?>
        </p>
    <? } ?>
    <? if ($this->row->author_parameters_display_email == 1) { ?>
        <h5>
            <? echo $this->row->author_email; ?>
        </h5>
    <? } ?>
    <p>
        <? echo $this->row->author_about_me; ?>
    </p>
</section>
