<?
/**
 * Portlet Wrap View
 *
 * @package   Molajo
 * @license   http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright 2013 Amy Stephen. All rights reserved.
 */
?>
<div class="portlet-header">
    <? if ($this->parameters->criteria_title == '') {
    } else {
        ?>
        <h4><? echo $this->parameters->criteria_title; ?></h4>
    <? } ?>
</div>
<div class="portlet-content">
