<?
/**
 * Gallery Template View
 *
 * @package   Molajo
 * @license   http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright 2013 Amy Stephen. All rights reserved.
 */
use Molajo\Service;


$nowrap = '';
$checked = '';
$rowCount = $this->registry->get('Grid', 'Tablerows'); ?>
<table class="grid responsive">
    <thead>
    <tr>
        <?
        $count = 1;
        $columnArray = $this->registry->get('Grid', 'Tablecolumns');
        foreach ($columnArray as $column) {
            $extraclass = '';
            $nowrap     = '';
            if ($count == 1) {
                $extraclass .= 'first';
                $nowrap = ' nowrap';
            }
            if ($count == count($columnArray)) {
                $extraclass .= 'last';
            }
            if ($extraclass == '') {
            } else {
                $extraclass = ' class="' . trim($extraClass) . '"';
            }
            ?>
            <th<? echo $extraclass . $nowrap; ?>><span><? echo $this->language->translate(
                        'GRID_' . strtoupper($column) . '_COLUMN_HEADING'
                    ); ?></span></th>
            <?
            $count ++;
        } ?>
        <th width="1%">
            <input type="checkbox" class="checkall">
        </th>
    </tr>
    </thead>
    <tbody>
