<?
/**
 * Gridsticky Template View
 *
 * @package   Molajo
 * @license   http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright 2013 Amy Stephen. All rights reserved.
 */
use Molajo\Service;


$action = $this->registry->get('Page', 'page_url');
//if ($this->row->enable == 1) {
?>
    <div class="grid-sticky grid-batch">
        <ol class="grid-batch">
            <li><strong><? echo $this->language->translate('Sticky Assignment'); ?></strong></li>
            <li><input type="submit" class="submit button small radius" name="submit" id="Sticky" value="Sticky"></li>
            <li><input type="submit" class="submit button small radius" name="submit" id="Unsticky" value="Unsticky">
            </li>
        </ol>
    </div>
<? //}
