<?
/**
 * Dummy Template View
 *
 * @package   Molajo
 * @license   http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright 2013 Amy Stephen. All rights reserved.
 */


$template = ucfirst(strtolower($this->row->fieldset_template_view));
$parameters = $this->row->fieldset_template_view_parameter; ?>
<include type=template name=<? echo $template; ?> parameter=<? echo $parameters; ?> wrap=div
         wrap_id=<? echo $parameters; ?>/>
