<?
/**
 * Customfields Template View
 *
 * @package   Molajo
 * @license   http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright 2013 Amy Stephen. All rights reserved.
 */
use Molajo\Service;


if ($this->row->new_fieldset == '1') {
    if ($this->row->page_first_row == 'first') {
    } elseif ((int)$this->row->first_following === 1) {
        ?>
        </ol>
        </fieldset>
    <? } else { ?>
        </tbody>
        </table>
        </fieldset>
    <? } ?>
    <? if ($this->row->fieldset_title == 'Create') { ?>
        <fieldset class="two-up">
        <legend><? echo $this->row->fieldset_title; ?></legend>
        <? if ($this->registry->get('parameters', 'application_help') == 1) { ?>
            <p><? echo $this->row->fieldset_description; ?></p>
        <? } ?>
        <ol>
    <? } else { ?>
        <fieldset>
        <legend><? echo $this->row->fieldset_title; ?></legend>
        <? if ($this->registry->get('parameters', 'application_help') == 1) { ?>
            <p><? echo $this->row->fieldset_description; ?></p>
        <? } ?>
        <table class="responsive">
        <thead>
        <tr>
            <th class="name"><? echo $this->language->translate('Name'); ?></th>
            <th class="type"><? echo $this->language->translate('Type'); ?></th>
            <th class="required"><? echo $this->language->translate('Required'); ?></th>
            <th class="datalist"><? echo $this->language->translate('List'); ?></th>
            <th class="hidden"><? echo $this->language->translate('Hidden'); ?></th>
            <th width="1%">
                <? echo $this->language->translate('Delete'); ?>
            </th>
        </tr>
        </thead>
        <tbody>
    <?
    }
} ?>

<? if ($this->row->tab_fieldset_title == 'Create') { ?>
    <li>
        <? echo $this->row->view;
        die;
        ?>
        <include type=template name=<? echo $this->row->view; ?> parameter_np=<? echo $this->row->name; ?>/>
    </li>

<? } else { ?>
    <tr>
        <td class="name"><? echo $this->language->translate($this->row->label); ?></td>
        <td class="type"><? echo $this->row->type; ?></td>
        <td class="required"><? $this->row->required; ?></td>
        <td class="datalist"><? echo $this->row->datalist; ?></td>
        <td class="hidden"><? echo $this->row->hidden; ?></td>
        <td><a href="#" class="small button alert radius"><? echo $this->language->translate(
                    'Delete',
                    'Delete'
                ); ?></a></td>
    </tr>
<?
}
