<?
/**
 * Gridcheckin Template View
 *
 * @package   Molajo
 * @license   http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright 2013 Amy Stephen. All rights reserved.
 */
use Molajo\Service;


$action = $this->registry->get('Page', 'page_url');
if ($this->row->enable == 1) {
    ?>
    <div class="grid-checkin grid-batch">
        <ol class="grid-batch">
            <li><strong><? echo $this->language->translate('Checkin Content'); ?></strong></li>
            <li><input type="submit" class="submit button small radius" name="submit" id="Checkin" value="Checkin"/>
            </li>
        </ol>
    </div>
<?
}
